required = ["k8s.io/code-generator/cmd/client-gen"]

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    go-tests = false

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.9.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.9.14"

[[constraint]]
  name = "github.com/openfaas/faas-netes"
  version = "0.7.8"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "v0.2.0"


